trigger:
- main
 
stages:
# ---------- Build Stage ----------
- stage: Build
  displayName: "Build Hello World App"
  jobs:
  - job: Build
    pool:
      name: apool
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/helloapp.zip'
        replaceExistingArchive: true
 
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
 
# ---------- Deploy Stage ----------
- stage: Deploy
  displayName: "Deploy to Azure VMSS via Environment"
  jobs:
  - deployment: DeployToVMSS
    displayName: "Deploy Hello World"
    pool:
      name: apool 
    environment:
      name: "env"
      resourceType: VirtualMachine  
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
 
          - script: |
              unzip $(Pipeline.Workspace)/drop/helloapp.zip -d helloapp
              cd helloapp
              chmod +x install.sh
              ./install.sh
            displayName: "Run install.sh on VMSS instance"
 




